=== lihaijun123/oss/oss-paint/src/main/webapp/WEB-INF/config/function-config.dtd
<!--  -->
<!ENTITY % Loop "(true|false|yes|no)">
<!ENTITY % SqlType "(select|insert|update|delete|procedure)">
<!ENTITY % SelectType "(get|check)">
<!ENTITY % ErrMsg "CDATA">
<!ENTITY % DataValue "CDATA">
<!ENTITY % BeanName "CDATA">
<!ENTITY % ConfigFileType "(systemFile|classPath)">
<!-- 1:普通分页方式；2：rownum<?在前的分页方式（默认方式）；3：rowid的使用方式，此类方式要在sql中添加rownum rid的伪字段 -->
<!ENTITY % pageType "(1|2|3)">
<!-- global function config -->
<!ELEMENT function-config (extend-config?,global-sql?,system*)>
<!--  -->
<!ELEMENT extend-config (config-file*)>

<!ELEMENT config-file EMPTY>
<!ATTLIST config-file  path					CDATA              		#REQUIRED>
<!ATTLIST config-file  type					%ConfigFileType;    		#IMPLIED>

<!-- system system -->
<!ELEMENT system (global-sql?,function*)>
<!ATTLIST system  sysId						CDATA              		#REQUIRED>

<!--  -->
<!ELEMENT global-sql (sql*)>



<!-- one function -->
<!ELEMENT function (execute-sql?,func-sql*,chart?)>
<!ATTLIST function  id							CDATA              		#REQUIRED>
<!-- a special java class implements com.nl.uitool.UIToolDataExecuter witch will to execute business logic -->
<!ATTLIST function  beanName					%BeanName;         		#IMPLIED>
<!ATTLIST function  message		  				CDATA					#IMPLIED>
<!-- datasource name -->
<!ATTLIST function  dsname		  				CDATA					#IMPLIED>
<!-- whether to init fetch -->
<!ATTLIST function  initFetch	  				%Loop;					#IMPLIED>
<!--  -->
<!ELEMENT execute-sql (sql*)>

<!--  -->
<!ELEMENT sql  (#PCDATA)>
<!ATTLIST sql  id								CDATA              		#REQUIRED>
<!-- witch special class will implement com.nl.uitool.UIToolExeSqlCreate interface -->
<!ATTLIST sql  creator							CDATA              		#IMPLIED>
<!--  -->
<!ATTLIST sql  pageType							%pageType;          		#IMPLIED>

<!--  -->
<!ELEMENT func-sql (params*)>
<!ATTLIST func-sql  id             				CDATA					#REQUIRED>
<!ATTLIST func-sql  sqlId						CDATA					#REQUIRED>
<!ATTLIST func-sql  loop           				%Loop;					#IMPLIED>
<!ATTLIST func-sql  sqlType        				%SqlType;				#REQUIRED>
<!ATTLIST func-sql  selectType     				%SelectType;			#IMPLIED>
<!ATTLIST func-sql  argGroup     				CDATA					#IMPLIED>
<!-- when the loop attribute is true and this property has value , then current sql loop with this -->
<!ATTLIST func-sql  mainLoopParam  				CDATA					#IMPLIED>
<!ATTLIST func-sql  stmtField	  				CDATA					#IMPLIED>
<!-- defined a special class witch implement com.nl.uitool.UIToolDataExecuter -->
<!ATTLIST func-sql  executer	  				CDATA					#IMPLIED>

<!--  -->
<!ELEMENT params (param*)>
<!ATTLIST params	id							CDATA              		#REQUIRED>
<!ATTLIST params	errMsg						%ErrMsg;				#IMPLIED>

<!--  -->
<!ELEMENT param EMPTY>
<!ATTLIST param	id								CDATA              		#REQUIRED>
<!ATTLIST param	value							%DataValue;				#IMPLIED>
<!ATTLIST param	alias							%DataValue;				#IMPLIED>
<!ATTLIST param	sequence						%DataValue;				#IMPLIED>
<!ATTLIST param	defaultValue					%DataValue;				#IMPLIED>
<!ATTLIST param	loop							%Loop;					#IMPLIED>

<!-- defined chart info -->
<!ELEMENT chart (subchart*)>
<!ATTLIST chart	sqlId							CDATA              		#REQUIRED>
<!ATTLIST chart	cretaor							CDATA              		#REQUIRED>

<!ELEMENT subchart (ydim?,xdim?,datadim*,properties?)>
<!ATTLIST subchart	id							CDATA              		#REQUIRED>


<!ELEMENT xdim EMPTY>
<!ATTLIST xdim	id								CDATA              		#REQUIRED>
<!ATTLIST xdim	title							CDATA              		#IMPLIED>


<!ELEMENT ydim EMPTY>
<!ATTLIST ydim	id								CDATA              		#REQUIRED>
<!ATTLIST ydim	title							CDATA              		#IMPLIED>

<!ELEMENT datadim EMPTY>
<!ATTLIST datadim	id							CDATA              		#REQUIRED>
<!ATTLIST datadim	title						CDATA              		#IMPLIED>

<!ELEMENT properties (property*)>
<!ELEMENT property (property*)>
<!ATTLIST property	id							CDATA              		#REQUIRED>
<!ATTLIST property	value						CDATA              		#IMPLIED>

=== lihaijun123/oss/oss-paint/src/main/webapp/WEB-INF/config/extend-configs/admin/function-config-admin-parameter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE uitool PUBLIC "-//NewLand UITool //DTD Direct Web Remoting 1.0//EN" "../function-config.dtd">
<!-- main config file ,this config file is required -->
<function-config>
	<system sysId="0000">
		<function id="262" beanName="">
			<execute-sql>
				<sql id="oss_admin_parameter_list">
					<![CDATA[
SELECT * FROM OSS_ADMIN_PARAMETER WHERE 1=1
]]>
				</sql>
			</execute-sql>
			<func-sql id="1" sqlId="oss_admin_parameter_list"
				loop="false" sqlType="select" argGroup="0" executer="">
				<params id="" errMsg="查詢系統參數列表出錯"></params>
			</func-sql>
		</function>

		<function id="914" beanName="">
			<execute-sql>
				<sql id="oss_admin_parameter_add">
					<![CDATA[
INSERT INTO OSS_ADMIN_PARAMETER
  (RECORD_ID,
   WEBSITE,
   PARAMETER_TYPE,
   PARAMETER_NAME,
   PARAMETER_KEY,
   PARAMETER_VALUE,
   PARAMETER_ORDER)
VALUES
  (&RECORD_ID,
   &WEBSITE,
   &PARAMETER_TYPE,
   &PARAMETER_NAME,
   &PARAMETER_KEY,
   &PARAMETER_VALUE,
   &PARAMETER_ORDER)
]]>
				</sql>
			</execute-sql>
			<func-sql id="1" sqlId="oss_admin_parameter_add"
				loop="false" sqlType="insert" argGroup="0" executer="">
				<params id="" errMsg="查詢系統參數列表出錯">
					<param id="RECORD_ID" sequence="S_OSS_ADMIN_PARAMETER"/>
				</params>
			</func-sql>
		</function>
		<function id="915" beanName="">
			<execute-sql>
				<sql id="oss_admin_parameter_view">
					<![CDATA[
SELECT * FROM OSS_ADMIN_PARAMETER WHERE RECORD_ID=&RECORD_ID
]]>
				</sql>
				<sql id="oss_admin_parameter_upd">
					<![CDATA[
UPDATE OSS_ADMIN_PARAMETER
SET WEBSITE         = &WEBSITE,
    PARAMETER_TYPE  = &PARAMETER_TYPE,
    PARAMETER_NAME  = &PARAMETER_NAME,
    PARAMETER_KEY   = &PARAMETER_KEY,
    PARAMETER_VALUE = &PARAMETER_VALUE,
    PARAMETER_ORDER = &PARAMETER_ORDER
WHERE RECORD_ID = &RECORD_ID
]]>
				</sql>
			</execute-sql>
			<func-sql id="1" sqlId="oss_admin_parameter_view"
				loop="false" sqlType="select" argGroup="0" executer="">
				<params id="" errMsg="查詢系統參數列表出錯"></params>
			</func-sql>
			<func-sql id="2" sqlId="oss_admin_parameter_upd"
				loop="false" sqlType="update" argGroup="0" executer="">
				<params id="" errMsg="查詢系統參數列表出錯"></params>
			</func-sql>
		</function>
	</system>
</function-config>
