=== lihaijun123/oss/oss-core/src/main/resources/config/table/table.dtd
<?xml version="1.0" encoding="BIG5"?>
<!ELEMENT tables (
	table*
)>
<!ELEMENT table (
	columns,roles?,action?
)>
<!ATTLIST table name ID #REQUIRED>
<!ATTLIST table pageDataSize CDATA #IMPLIED>
<!ATTLIST table displayName CDATA #REQUIRED>
<!ATTLIST table schema CDATA #REQUIRED>
<!ATTLIST table dataSource CDATA #REQUIRED>
<!ATTLIST table dataConstructEngine (jdbc_sql | jdbc_table |hibernate_object | hiberante_hql | ibatis_sql ) "jdbc_table">

<!ELEMENT columns ( column*)>

<!ELEMENT column (
	(searchCondition)*,(foreignTable)?
)>

<!ATTLIST column name CDATA #REQUIRED>
<!ATTLIST column displayName CDATA #IMPLIED>
<!ATTLIST column visible (true | false) "true">
<!ATTLIST column type CDATA #IMPLIED>
<!ATTLIST column sortable (true | false) "true">
<!ATTLIST column searchable (true | false) "true">
<!ATTLIST column displayType (input | image | link | list) "input">
<!ATTLIST column url CDATA #IMPLIED>
<!ATTLIST column order CDATA #IMPLIED>
<!ATTLIST column width CDATA #IMPLIED>
<!ATTLIST column searchType (input | list | date) "input">
<!ATTLIST column nameUrl CDATA #IMPLIED>
<!ATTLIST column parameterName CDATA #IMPLIED>

<!ELEMENT roles ( role*)>
<!ELEMENT role (
	(searchCondition)*
)>
<!ATTLIST role name CDATA #REQUIRED>
<!ATTLIST role scope CDATA #IMPLIED>



<!ELEMENT searchCondition EMPTY>
<!ATTLIST searchCondition name (e | m | l | me | le | like | n | str) "e">
<!ATTLIST searchCondition displayName CDATA  #IMPLIED>

<!ELEMENT action EMPTY>
<!ATTLIST action delete CDATA  #IMPLIED>
<!ATTLIST action view CDATA  #IMPLIED>
<!ATTLIST action modify CDATA  #IMPLIED>
<!ATTLIST action bulkDelete CDATA  #IMPLIED>

<!ELEMENT foreignTable EMPTY>
<!ATTLIST action name CDATA  #IMPLIED>
<!ATTLIST action key CDATA  #IMPLIED>
<!ATTLIST action value CDATA  #IMPLIED>

=== lihaijun123/oss/oss-core/src/main/resources/config/table/table.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE tables PUBLIC "" "table.dtd">
<tables>
	<table displayName="ノめ" name="aaa" schema="micOss2005" dataSource="OSS_ADMIN_USER" pageDataSize = "4" >
		<columns>
			<column name="USER_ID"  displayName="ノめID" type = 'int' sortable="true" url="/test.do?id=~USER_ID~" >
			<searchCondition name = "me"  displayName="ノめID"  />		
			<searchCondition name = "le"  displayName="ノめID"  />		
			</column>
		
		<column name="FULLNAME"  displayName=""  type = 'String' sortable="false" >
			<searchCondition name = "str"  displayName="" />			
		</column>

	<column name="LOGIN_NAME"  displayName="祅嘲" type = 'String' searchable = "false" sortable="true" url="/test.do?id=#sessionName#">
			<searchCondition name = "e"  displayName="祅嘲"/>			
	</column>

	<column name="GENDER"  displayName="┦"  type = "int" searchType = "list" parameterName="PARAM_TYPE_SEX" sortable="false">
			<searchCondition name = "e" displayName="┦"/>			
	</column>

	<column name="EMAIL"  displayName="EMAIL"  type = 'String' searchable = "false"  width="200"  sortable="false">					
	</column>

<column name="CREATED_TIME"  displayName="承丁" type = 'datetime' searchable = "true"  searchType = "date"  width="200" sortable="false">	
			<searchCondition name = "m"  displayName="承丁"/>		
	</column>


		</columns>
		
		<action view = "/delete.do?id=~USER_ID~" modify = "/delete.do?id=~USER_ID~" bulkDelete="/getTable.do?method=kk&amp;name=~FULLNAME~" />
		<roles>
			<role name="id" scope="id = ?"></role>
		</roles>
	</table>
	
	
	
		
		<table displayName="ノめ" name="bbb" schema="mic2005" dataSource="CORE_COMPANY_CN_MAINT_CHK" pageDataSize = "20" >
		<columns>
			<column name="COM_ID"  displayName="ノめID"  type = 'int' sortable="true" url="/test.do?id=~COM_ID~" >
			<searchCondition name = "n" displayName="ノめID"  />			
			</column>	
		</columns>
	<action  bulkDelete="/getTable.do?method=kk&amp;name=~COM_ID~" />
		<roles>
			<role name="id" scope="id = ?"></role>
		</roles>
	</table>
	
	

	
</tables>

=== lihaijun123/oss/oss-core/src/main/resources/config/table/OSS_ADMIN_RESOURCE.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE tables PUBLIC "" "table.dtd">
<tables>
	<table displayName="戈方" name="ccc" schema="micOss2005" dataSource="OSS_ADMIN_RESOURCE" pageDataSize = "20" >
		<columns>
			<column name="RESOURCE_ID"  displayName="戈方ID"  type = 'int' sortable="true"  >
			<searchCondition name = "me"  displayName="戈方ID"  />		
			<searchCondition name = "le"  displayName="戈方ID"  />	
			</column>	
			
			<column name="RESOURCE_NAME"  displayName="戈方" type = 'String' searchable = "true" sortable="true" url="/test.do?id=~RESOURCE_ID~">
			<searchCondition name = "e"  displayName="戈方"/>			
			</column>
			
				<column name="RESOURCE_TYPE"  displayName="戈方摸" type = 'String'  searchType = "list"  searchable = "true"   parameterName="PARAM_TYPE_RESOURCE_TYPE" sortable="false" >		
				<searchCondition name = "e"  displayName="戈方摸"/>						
			</column>
			
			<column name="RESOURCE_DISPLAY"  displayName="戈方琌陪ボ" type = 'String' searchType = "list"   parameterName="PARAM_TYPE_DISPLAY">		
						
			</column>
			
			
			<column name="DESCRIPTION"  displayName="磞瓃" type = 'String' searchable = "true" sortable="false">	
			<searchCondition name = "like"  displayName="磞瓃"/>					
			</column>
			
			
		</columns>
		<action  bulkDelete="/getTable.do?method=kk&amp;name=~RESOURCE_ID~" />
		<roles>
			<role name="id" scope="id = ?"></role>
		</roles>
	</table>
	
</tables>
